### ISSUE TITLE
issue analyzing wav files 

### ISSUE THREAD

**Issue by 3216alec** [SPRITZ-Research-Group/Skype-Type#1]
./generate_model.py test.wav test.txt folder3/model
Found 0 files already mined
Found 1 files to mine
Processing file #1
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alec/Desktop/yo/dst/dispatchers.py", line 22, in offline
    for data in iter(in_queue.get, None):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[test.txt](https://github.com/SPRITZ-Research-Group/Skype-Type/files/1370717/test.txt)

[test.wav.txt](https://github.com/SPRITZ-Research-Group/Skype-Type/files/1370726/test.wav.txt)
actually a wav file

**Comment by dantt** [comment]
Hi. Thanks for providing the test files.
Your text.txt is wrong -- you need one target character per line.
It should look like this:
q
w
e
r



However, single-character ground truth files should be allowed - this is now fixed.
In particular in this case now the error message is more informative (saying that it expected only a single character).
Thanks for the report.
